project:
  type: website
  output-dir: docs

website:
  title: "slinberg.net"
  description: Steve Linberg's blog
  site-url: https://slinberg.net
  repo-url: https://github.com/stevelinberg/quarto-blog
  repo-actions: [edit, issue, source]
  reader-mode: true
  navbar:
    search: true
    right:
      - text: About
        href: steve.qmd
      - text: "Blog"
        href: "blog.qmd"
      - icon: twitter
        href: https://twitter.com/stevelinberg
      - icon: linkedin
        href: https://www.linkedin.com/in/slinberg/
      - icon: github
        href: https://github.com/stevelinberg
      - icon: stack-overflow
        href: https://stackoverflow.com/users/13603796/stevelinberg
      - icon: envelope
        href: mailto:steve@slinberg.net
      - icon: rss
        href: index.xml
    feed:
      items: 20

format:
  html:
    theme:
      light: flatly
      dark: darkly
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    toc-title: On this page
    toc-location: right
editor: visual

execute:
  freeze: true
  

